name: Red Diamond Events
favicon: null
layout_spectrum: 0.554685523500666
typography_spectrum: 0.746668797917664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.40220347233116627
  lightness: 0.7120757636148483
  saturation: 0.6723629492335021
  rhythmicContrast: 0.6307514526415616
purpose: []
