name: RedDiamondEvents
favicon: null
layout_spectrum: 0.8208
typography_spectrum: 0.13203
title: Red Diamond Events
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#beb7ba'
    - '#553e2d'
    - '#93679e'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
