analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#f20000'
    - '#666666'
    - '#f99595'
  brandStrength: 0.3125
  lightness: 0.6875
  rhythmicContrast: 0.75
  saturation: 0.6875
cta: {}
layout_spectrum: 0.24278
name: Red Diamond Events
opengraph: {}
purpose: []
typography_spectrum: 0.5617
